name: Build website

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: macos-12
    name: Build with Pelican
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - run: pipenv install --ignore-pipfile
      - name: Build dev
        run: pipenv run pelican -s pelicanconf.py
      - name: Build publish
        run: pipenv run pelican -s pelicanconfpublish.py
